name: Genrate ASCII Artwork

on:
  push

jobs:
  ascii_job:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      run: actions/checkout@v4
    
    - name: List Repo Files
      run: ls -ltra

    - name: Exec Shell Script
      run: ./ascii-script.sh