name: Genrate ASCII Artwork

on:
    push

jobs:
    build_job_1:
        runs-on: ubuntu-latest
        steps:
        - name: Install Cowsay Program
          run: sudo apt-get install cowsay -y

        - name: Execute Cowsay CMD
          run: cowsay -f dragon "Run for cover, I am a Dragon....RAWR" >> dragon.txt

        - name: Upload Dragon text file
          uses: actions/upload-artifact@v4
          with:
            name: dragon-ascii
            path: ./dragon.txt

    test_job_2:
        needs: build_job_1
        runs-on: ubuntu-latest
        steps:
        - name: Sleep for 10 seconds
          run: sleep 10

        - name: Download Dragon ASCII
          uses: actions/download-artifact@v4
          with:
            name: dragon-ascii

        - name: Display structure of downloaded files
          run: ls -R

        - name: Test the file exists
          run: grep -l "dragon" dragon.txt

    deploy_job_3:
        needs: test_job_2
        runs-on: ubuntu-latest
        steps:
        - name: Download Dragon ASCII
          uses: actions/download-artifact@v4
          with:
            name: dragon-ascii
  
        - name: Read File
          run: cat dragon.txt

        - name: Deploy
          run: echo Deploying... .. .

