name: Exploring Variables, Secrets and Workflow Triggers 

on:
  workflow_dispatch: 
 # schedule:
 #   - cron: "*/1 * * * *"
# push
# Variable at the workflow level
env: 
    CONTAINER_REGISTRY: docker.io
    IMAGE_NAME: github-actions-nginx
jobs:
    docker:
        runs-on: ubuntu-latest
        steps:
        - name: Docker Build
          run: echo docker build -t $CONTAINER_REGISTRY/${{ vars.DOCKER_USERNAME }}/$IMAGE_NAME:latest

        - name: Docker Login
            # Secret defined in repo settings 
          run: echo docker login --username=${{ vars.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }}

        - name: Docker Publish
          run: echo docker push $CONTAINER_REGISTRY/${{ vars.DOCKER_USERNAME }}/$IMAGE_NAME:latest

    deploy:
        needs: docker
        concurrency: 
          group: production-deployment
          cancel-in-progress: false #true will make any new jobs stop the previous and #False will make any new jobs wait for for the first to complete similar to needs
        runs-on: ubuntu-latest
        steps:
        - name: Docker Run
          run: echo docker run -d -p 8080:80 $CONTAINER_REGISTRY/${{ vars.DOCKER_USERNAME }}/${{ env.IMAGE_NAME}}:latest


        
    